# Generated by Django 5.2.16 on 2026-08-23 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='login_otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='login_otp_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
