# Generated by Django 5.2.16 on 2026-07-30 07:57

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('contact_number', models.CharField(db_index=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (7-19 digits, optionally starting with +).', regex='^\\+?[0-9][0-9\\s\\-]{7,18}$')])),
                ('category', models.CharField(choices=[('insurance', 'Insurance'), ('permit', 'Permit'), ('fitness_puc', 'Fitness / PUC'), ('license', 'License')], db_index=True, max_length=20)),
                ('vehicle_number', models.CharField(blank=True, max_length=20, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, db_index=True, null=True)),
                ('amount_total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('needs_reminder', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category'], name='customers_c_categor_f85c24_idx'), models.Index(fields=['end_date'], name='customers_c_end_dat_13391b_idx'), models.Index(fields=['contact_number'], name='customers_c_contact_17692b_idx')],
            },
        ),
    ]
