# Generated by Django 5.2.16 on 2026-08-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_categories_and_service_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='category',
            field=models.CharField(choices=[('insurance', 'Insurance'), ('permit', 'Permit'), ('fitness', 'Fitness'), ('puc', 'PUC'), ('tax', 'Tax'), ('fitness_puc', 'Fitness / PUC'), ('license', 'License')], db_index=True, max_length=20),
        ),
    ]
