# Generated by Django 5.2.16 on 2026-08-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_split_legacy_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='reference_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
